/**
 * Deterministic Recommendation Engine
 *
 * Generates candidate recommendations purely from Gold-layer scored KPI data.
 * NO LLM involved at this stage — outputs are deterministic and reproducible.
 *
 * CRITICAL INVARIANTS:
 * - This function is pure: same Gold snapshots → same candidates (no side effects)
 * - No external calls, no DB reads, no async IO — purely functional
 * - LLM receives these candidates for enrichment ONLY (summarize, explain, humanize)
 * - LLM is never the authoritative source of a recommendation
 * - Every candidate includes `evidence[]` and `deterministic_reason` (audit trail)
 *
 * Architecture position (from plan):
 *   Gold layer → Deterministic Engine → candidates → LLM enrichment → recommendations
 *
 * Recommendation types (7):
 *   reduce_retention    — composite + time_span_days suggests over-retention
 *   optimize_searches   — high search cost + low utilization
 *   decommission        — composite < 20 AND last activity > 90 days
 *   upgrade_sourcetype  — parsing_error_rate > 15%
 *   consolidate_index   — utilization < 5 AND similar named index detected
 *   increase_detection  — detection < 30 AND security-relevant sourcetype
 *   archive_cold        — zero activity > 180 days
 */

import { GoldRow } from './gold-scorer';

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

export type RecommendationType =
  | 'reduce_retention'
  | 'optimize_searches'
  | 'decommission'
  | 'upgrade_sourcetype'
  | 'consolidate_index'
  | 'increase_detection'
  | 'archive_cold';

export type RecommendationPriority = 'critical' | 'high' | 'medium' | 'low';

export interface RecommendationEvidence {
  field: string;
  value: number | string | boolean;
  threshold?: number | string;
  interpretation: string;
}

export interface RecommendationCandidate {
  type: RecommendationType;
  index_name: string;
  tenant_id: string;
  priority: RecommendationPriority;
  /** Estimated monthly savings in GB-days or cost units */
  savings_estimate: number;
  /** Human-readable reason generated by deterministic logic (not LLM) */
  deterministic_reason: string;
  /** Data points that triggered this recommendation */
  evidence: RecommendationEvidence[];
  /** Input Gold snapshot that generated this candidate */
  gold_snapshot_id: string;
  /** Scoring version of the Gold snapshot */
  scoring_version: string;
  /** Composite score of the index at recommendation time */
  composite_score: number;
  /** Tier of the index at recommendation time */
  tier: string;
}

// ─────────────────────────────────────────────
// Constants — thresholds are deterministic invariants
// ─────────────────────────────────────────────

const THRESHOLDS = {
  DECOMMISSION_COMPOSITE_MAX: 20,
  ARCHIVE_COLD_DAYS: 180,
  UPGRADE_SOURCETYPE_ERROR_RATE: 15,   // %
  LOW_UTILIZATION: 5,                   // score units
  LOW_DETECTION: 30,                    // score units
  MEDIUM_DETECTION: 50,                 // score units for "could improve"
  REDUCE_RETENTION_MIN_COMPOSITE: 40,   // good index but high retention waste
  OPTIMIZE_SEARCHES_MAX_UTILIZATION: 30,
} as const;

const SECURITY_SOURCETYPES = new Set([
  'wineventlog', 'xmlwineventlog', 'syslog', 'pan:traffic', 'pan:threat',
  'cisco:asa', 'aws:cloudtrail', 'okta:im2', 'crowdstrike', 'defendpoint',
  'o365:management:activity', 'stream:http', 'suricata', 'zeek',
  'aws:elb:accesslogs', 'azure:audit', 'gsuite:reports:activity',
  'duo', 'sentinelone', 'cylance', 'carbonblack'
]);

// ─────────────────────────────────────────────
// Main entry point
// ─────────────────────────────────────────────

/**
 * Generate deterministic recommendation candidates from Gold KPI snapshots.
 *
 * This is the ONLY function in this module that callers should use directly.
 * LLM enrichment happens downstream — this function has no LLM dependency.
 *
 * @param snapshots  Current-validity Gold rows (validity_closed_at IS NULL)
 * @returns          Sorted candidate list (priority DESC, savings_estimate DESC)
 */
export function generateCandidates(snapshots: GoldRow[]): RecommendationCandidate[] {
  if (snapshots.length === 0) return [];

  const candidates: RecommendationCandidate[] = [];

  // Build a lookup for consolidation detection (similar index names)
  const indexNames = new Set(snapshots.map(s => s.index_name));

  for (const snapshot of snapshots) {
    // Each check is independent — a single index can generate multiple candidates
    const archiveCold = checkArchiveCold(snapshot);
    if (archiveCold) candidates.push(archiveCold);

    const decommission = checkDecommission(snapshot);
    if (decommission) candidates.push(decommission);

    const upgradeSourcetype = checkUpgradeSourcetype(snapshot);
    if (upgradeSourcetype) candidates.push(upgradeSourcetype);

    const increaseDetection = checkIncreaseDetection(snapshot);
    if (increaseDetection) candidates.push(increaseDetection);

    const reduceRetention = checkReduceRetention(snapshot);
    if (reduceRetention) candidates.push(reduceRetention);

    const consolidate = checkConsolidateIndex(snapshot, indexNames);
    if (consolidate) candidates.push(consolidate);

    const optimizeSearches = checkOptimizeSearches(snapshot);
    if (optimizeSearches) candidates.push(optimizeSearches);
  }

  // Sort: critical first, then by savings_estimate DESC
  return candidates.sort((a, b) => {
    const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 };
    const pDiff = priorityOrder[a.priority] - priorityOrder[b.priority];
    if (pDiff !== 0) return pDiff;
    return b.savings_estimate - a.savings_estimate;
  });
}

// ─────────────────────────────────────────────
// Individual checks (each returns null if no recommendation)
// ─────────────────────────────────────────────

function checkArchiveCold(s: GoldRow): RecommendationCandidate | null {
  // Zero detection + near-zero utilization + no activity for extended period
  // We use time_span_days from silver (not available here directly) but
  // infer from composite_score being very low + utilization near-zero
  if (s.utilization_score > 2 || s.composite_score > 10) return null;

  // Gold layer doesn't have time_span_days directly — use composite + utilization as proxy
  // A composite < 5 with utilization < 2 strongly suggests cold/abandoned index
  return {
    type: 'archive_cold',
    index_name: s.index_name,
    tenant_id: s.tenant_id,
    priority: 'high',
    savings_estimate: estimateSavings(s, 'archive_cold'),
    deterministic_reason:
      `Index "${s.index_name}" has composite score ${s.composite_score.toFixed(1)} ` +
      `and utilization score ${s.utilization_score.toFixed(1)}, indicating no meaningful ` +
      `activity. Archive to cold storage or decommission.`,
    evidence: [
      {
        field: 'composite_score',
        value: s.composite_score,
        threshold: 10,
        interpretation: 'Composite score below cold-archive threshold of 10'
      },
      {
        field: 'utilization_score',
        value: s.utilization_score,
        threshold: 2,
        interpretation: 'Near-zero utilization; no queries or dashboards consuming this data'
      }
    ],
    gold_snapshot_id: s.id,
    scoring_version: s.scoring_version,
    composite_score: s.composite_score,
    tier: s.tier
  };
}

function checkDecommission(s: GoldRow): RecommendationCandidate | null {
  if (s.composite_score >= THRESHOLDS.DECOMMISSION_COMPOSITE_MAX) return null;
  if (s.tier !== 'inactive' && s.tier !== 'low-value') return null;

  const isFullyDead = s.utilization_score < 1 && s.detection_score < 5;
  if (!isFullyDead) return null;

  return {
    type: 'decommission',
    index_name: s.index_name,
    tenant_id: s.tenant_id,
    priority: 'critical',
    savings_estimate: estimateSavings(s, 'decommission'),
    deterministic_reason:
      `Index "${s.index_name}" has composite score ${s.composite_score.toFixed(1)} ` +
      `(threshold: ${THRESHOLDS.DECOMMISSION_COMPOSITE_MAX}), utilization ` +
      `${s.utilization_score.toFixed(1)}, and detection ${s.detection_score.toFixed(1)}. ` +
      `This index provides no measurable value. Recommend decommissioning.`,
    evidence: [
      {
        field: 'composite_score',
        value: s.composite_score,
        threshold: THRESHOLDS.DECOMMISSION_COMPOSITE_MAX,
        interpretation: `Composite below decommission threshold of ${THRESHOLDS.DECOMMISSION_COMPOSITE_MAX}`
      },
      {
        field: 'utilization_score',
        value: s.utilization_score,
        threshold: 1,
        interpretation: 'Effectively zero utilization'
      },
      {
        field: 'detection_score',
        value: s.detection_score,
        threshold: 5,
        interpretation: 'No meaningful detection contribution'
      },
      {
        field: 'minimum_activity_gated',
        value: s.minimum_activity_gated,
        interpretation: s.minimum_activity_gated
          ? 'Score was gated by minimum activity rule'
          : 'Not gated — scores are authentic'
      }
    ],
    gold_snapshot_id: s.id,
    scoring_version: s.scoring_version,
    composite_score: s.composite_score,
    tier: s.tier
  };
}

function checkUpgradeSourcetype(s: GoldRow): RecommendationCandidate | null {
  // High parsing error rate = data quality issue = upgrade sourcetype config
  // We use quality_score as proxy: low quality + reasonable utilization
  if (s.quality_score >= 50) return null;
  if (s.utilization_score < 10) return null; // Dead index — decommission instead

  const impliedErrorRate = Math.max(0, 100 - s.quality_score * 2);
  if (impliedErrorRate < THRESHOLDS.UPGRADE_SOURCETYPE_ERROR_RATE) return null;

  return {
    type: 'upgrade_sourcetype',
    index_name: s.index_name,
    tenant_id: s.tenant_id,
    priority: 'high',
    savings_estimate: estimateSavings(s, 'upgrade_sourcetype'),
    deterministic_reason:
      `Index "${s.index_name}" has quality score ${s.quality_score.toFixed(1)}, ` +
      `implying ~${impliedErrorRate.toFixed(0)}% parsing error rate. ` +
      `Upgrading the sourcetype configuration or parser will improve field extraction and data reliability.`,
    evidence: [
      {
        field: 'quality_score',
        value: s.quality_score,
        threshold: 50,
        interpretation: `Quality below 50 indicates high parsing errors or poor field coverage`
      },
      {
        field: 'implied_parsing_error_rate',
        value: impliedErrorRate,
        threshold: THRESHOLDS.UPGRADE_SOURCETYPE_ERROR_RATE,
        interpretation: `Implied error rate exceeds ${THRESHOLDS.UPGRADE_SOURCETYPE_ERROR_RATE}% threshold`
      }
    ],
    gold_snapshot_id: s.id,
    scoring_version: s.scoring_version,
    composite_score: s.composite_score,
    tier: s.tier
  };
}

function checkIncreaseDetection(s: GoldRow): RecommendationCandidate | null {
  if (s.detection_score >= THRESHOLDS.LOW_DETECTION) return null;
  if (s.utilization_score < 15) return null; // Index isn't even being used well

  // Check if sourcetype is security-relevant
  const isSecurityRelevant = isSecuritySourcetype(s.index_name);
  if (!isSecurityRelevant) return null;

  return {
    type: 'increase_detection',
    index_name: s.index_name,
    tenant_id: s.tenant_id,
    priority: s.detection_score < 10 ? 'critical' : 'high',
    savings_estimate: 0, // Not a cost-saving recommendation — a value-add
    deterministic_reason:
      `Index "${s.index_name}" has detection score ${s.detection_score.toFixed(1)} ` +
      `(threshold: ${THRESHOLDS.LOW_DETECTION}) despite being a security-relevant data source. ` +
      `Adding correlation searches, alerts, or detection rules would improve the security value of this index.`,
    evidence: [
      {
        field: 'detection_score',
        value: s.detection_score,
        threshold: THRESHOLDS.LOW_DETECTION,
        interpretation: `Detection below minimum recommended threshold of ${THRESHOLDS.LOW_DETECTION} for security data`
      },
      {
        field: 'security_relevant',
        value: true,
        interpretation: 'Index name matches known security data source patterns'
      },
      {
        field: 'utilization_score',
        value: s.utilization_score,
        threshold: 15,
        interpretation: 'Index is actively used — detection improvement would have high ROI'
      }
    ],
    gold_snapshot_id: s.id,
    scoring_version: s.scoring_version,
    composite_score: s.composite_score,
    tier: s.tier
  };
}

function checkReduceRetention(s: GoldRow): RecommendationCandidate | null {
  // High-value index with unusually long implied retention window
  // Detected via: good composite score + very high raw event count
  // Retention optimization doesn't reduce value, just cost
  if (s.composite_score < THRESHOLDS.REDUCE_RETENTION_MIN_COMPOSITE) return null;
  if (s.tier !== 'medium-value' && s.tier !== 'high-value') return null;

  // Heuristic: if utilization is moderate but detection is low relative to the
  // index size, there is likely stale data being retained unnecessarily
  const hasLowDetectionRelativeToSize = s.utilization_score > 40 && s.detection_score < 30;
  if (!hasLowDetectionRelativeToSize) return null;

  return {
    type: 'reduce_retention',
    index_name: s.index_name,
    tenant_id: s.tenant_id,
    priority: 'medium',
    savings_estimate: estimateSavings(s, 'reduce_retention'),
    deterministic_reason:
      `Index "${s.index_name}" has utilization score ${s.utilization_score.toFixed(1)} ` +
      `but detection score ${s.detection_score.toFixed(1)}, suggesting data is being ` +
      `accessed frequently but not used for detection. Reducing the retention window ` +
      `would cut storage costs without impacting detection coverage.`,
    evidence: [
      {
        field: 'utilization_score',
        value: s.utilization_score,
        interpretation: 'High query volume indicates active use but not detection-focused'
      },
      {
        field: 'detection_score',
        value: s.detection_score,
        threshold: 30,
        interpretation: 'Low detection score relative to utilization — operational data pattern'
      },
      {
        field: 'composite_score',
        value: s.composite_score,
        interpretation: 'Index is valuable; reducing retention preserves value while cutting cost'
      }
    ],
    gold_snapshot_id: s.id,
    scoring_version: s.scoring_version,
    composite_score: s.composite_score,
    tier: s.tier
  };
}

function checkConsolidateIndex(s: GoldRow, allIndexNames: Set<string>): RecommendationCandidate | null {
  if (s.utilization_score >= THRESHOLDS.LOW_UTILIZATION) return null;

  // Look for another index with a similar name (prefix match, different suffix)
  const baseName = s.index_name.replace(/[-_](dev|test|qa|staging|old|backup|copy|v\d+|\d{4})$/i, '');
  const hasSimilarIndex = baseName !== s.index_name && allIndexNames.has(baseName);

  if (!hasSimilarIndex) return null;

  return {
    type: 'consolidate_index',
    index_name: s.index_name,
    tenant_id: s.tenant_id,
    priority: 'medium',
    savings_estimate: estimateSavings(s, 'consolidate_index'),
    deterministic_reason:
      `Index "${s.index_name}" has utilization score ${s.utilization_score.toFixed(1)} ` +
      `and a similar base-named index "${baseName}" exists. ` +
      `Consolidating these indexes would reduce management overhead and storage fragmentation.`,
    evidence: [
      {
        field: 'utilization_score',
        value: s.utilization_score,
        threshold: THRESHOLDS.LOW_UTILIZATION,
        interpretation: `Utilization below ${THRESHOLDS.LOW_UTILIZATION} — index is rarely queried`
      },
      {
        field: 'similar_index',
        value: baseName,
        interpretation: `Base index "${baseName}" exists — likely a duplicate or variant`
      }
    ],
    gold_snapshot_id: s.id,
    scoring_version: s.scoring_version,
    composite_score: s.composite_score,
    tier: s.tier
  };
}

function checkOptimizeSearches(s: GoldRow): RecommendationCandidate | null {
  if (s.utilization_score >= THRESHOLDS.OPTIMIZE_SEARCHES_MAX_UTILIZATION) return null;
  if (s.composite_score < 25) return null; // Very low value — decommission instead

  // Quality is fine but utilization is low — the queries are probably inefficient
  if (s.quality_score < 60) return null; // Data quality issue takes priority

  return {
    type: 'optimize_searches',
    index_name: s.index_name,
    tenant_id: s.tenant_id,
    priority: 'low',
    savings_estimate: estimateSavings(s, 'optimize_searches'),
    deterministic_reason:
      `Index "${s.index_name}" has low utilization score ${s.utilization_score.toFixed(1)} ` +
      `despite reasonable quality (${s.quality_score.toFixed(1)}). ` +
      `Review scheduled searches and alerts referencing this index for optimization opportunities.`,
    evidence: [
      {
        field: 'utilization_score',
        value: s.utilization_score,
        threshold: THRESHOLDS.OPTIMIZE_SEARCHES_MAX_UTILIZATION,
        interpretation: 'Low utilization with good data quality suggests search inefficiency'
      },
      {
        field: 'quality_score',
        value: s.quality_score,
        interpretation: 'Data quality is acceptable — the bottleneck is search usage'
      }
    ],
    gold_snapshot_id: s.id,
    scoring_version: s.scoring_version,
    composite_score: s.composite_score,
    tier: s.tier
  };
}

// ─────────────────────────────────────────────
// Helper functions
// ─────────────────────────────────────────────

/**
 * Estimate monthly cost savings (in abstract units) for a recommendation.
 * This is a heuristic based on score signals — NOT a precise financial model.
 * LLM enrichment can refine this with actual GB pricing if available.
 */
function estimateSavings(s: GoldRow, type: RecommendationType): number {
  switch (type) {
    case 'decommission':
      // Full elimination: savings proportional to inverse score
      return Math.round((100 - s.composite_score) * 1.5);
    case 'archive_cold':
      return Math.round((100 - s.composite_score) * 1.0);
    case 'reduce_retention':
      return Math.round(s.utilization_score * 0.5);
    case 'upgrade_sourcetype':
      // Quality improvement reduces re-indexing cost
      return Math.round((100 - s.quality_score) * 0.3);
    case 'consolidate_index':
      return Math.round((THRESHOLDS.LOW_UTILIZATION - s.utilization_score) * 2);
    case 'optimize_searches':
      return Math.round((THRESHOLDS.OPTIMIZE_SEARCHES_MAX_UTILIZATION - s.utilization_score) * 1.0);
    case 'increase_detection':
      return 0; // Value-add, not cost-saving
    default:
      return 0;
  }
}

function isSecuritySourcetype(indexName: string): boolean {
  const lower = indexName.toLowerCase();
  for (const st of SECURITY_SOURCETYPES) {
    if (lower.includes(st)) return true;
  }
  // Also match common security index naming conventions
  return /\b(security|soc|siem|endpoint|auth|waf|vpn|ids|ips)\b/i.test(indexName);
}
